version: 2.1

# Define a job to run the SonarQube scan
jobs:
  sonar_scan:
    docker:
      - image: cimg/node:current  # Use a Node.js image; replace with appropriate image for your project’s language
    steps:
      - checkout  # Checkout the code from GitHub

      - run:
          name: Install Dependencies
          command: npm install  # Adjust this command based on your project's dependencies

      - run:
          name: Run SonarQube Scan
          command: |
            npm install -g sonar-scanner  # Install SonarQube scanner
            sonar-scanner \
              -Dsonar.projectKey=ST10091023_APDS---sonarqube-pipeline \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=st10091023 \
              -Dsonar.login=$SONAR_TOKEN  # Token stored in CircleCI environment variables

workflows:
  version: 2
  sonar_scan_workflow:
    jobs:
      - sonar_scan
